(********************************************************)
(*           AUTOGENERATED FILE - DO NOT EDIT!          *)
(********************************************************)
(* Generated by: ocaml-protoc-plugin                    *)
(* https://github.com/andersfugmann/ocaml-protoc-plugin *)
(********************************************************)
(*
  Source: wandb/proto/wandb_base.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot=''
    opens=[]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
    prefix_output_with_package=false
*)
[@@@ocaml.alert "-protobuf"] (* Disable deprecation warnings for protobuf*)
(**/**)
module Runtime' = Ocaml_protoc_plugin [@@warning "-33"]
module Imported'modules = struct
end
(**/**)
module rec Wandb_internal : sig

  (**
{%html:
<p>_RecordInfo, _RequestInfo: extra info for all records and requests</p>
%}
  *)
  module rec P_RecordInfo : sig
    type t = {
      stream_id:string;
      _tracelog_id:string;
    }
    val make: ?stream_id:string -> ?_tracelog_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?stream_id:string -> ?_tracelog_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and P_RequestInfo : sig
    type t = (string)
    val make: ?stream_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?stream_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end


  (**
{%html:
<p>_ResultInfo: extra info for all results</p>
%}
  *)
  and P_ResultInfo : sig
    type t = (string)
    val make: ?_tracelog_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?_tracelog_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

end = struct
  module rec P_RecordInfo : sig
    type t = {
      stream_id:string;
      _tracelog_id:string;
    }
    val make: ?stream_id:string -> ?_tracelog_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?stream_id:string -> ?_tracelog_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = P_RecordInfo
    let name () = ".wandb_internal._RecordInfo"
    type t = {
      stream_id:string;
      _tracelog_id:string;
    }
    type make_t = ?stream_id:string -> ?_tracelog_id:string -> unit -> t
    let make ?(stream_id = {||}) ?(_tracelog_id = {||}) () = { stream_id; _tracelog_id }
    let merge =
    let merge_stream_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "stream_id", "streamId"), string, ({||})) ) in
    let merge__tracelog_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((100, "_tracelog_id", "TracelogId"), string, ({||})) ) in
    fun t1 t2 -> {
    	stream_id = (merge_stream_id t1.stream_id t2.stream_id);
    	_tracelog_id = (merge__tracelog_id t1._tracelog_id t2._tracelog_id);
     }
    let spec () = Runtime'.Spec.( basic ((1, "stream_id", "streamId"), string, ({||})) ^:: basic ((100, "_tracelog_id", "TracelogId"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { stream_id; _tracelog_id } -> serialize writer stream_id _tracelog_id

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor stream_id _tracelog_id = { stream_id; _tracelog_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { stream_id; _tracelog_id } -> serialize stream_id _tracelog_id
    let from_json_exn =
      let constructor stream_id _tracelog_id = { stream_id; _tracelog_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and P_RequestInfo : sig
    type t = (string)
    val make: ?stream_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?stream_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = P_RequestInfo
    let name () = ".wandb_internal._RequestInfo"
    type t = (string)
    type make_t = ?stream_id:string -> unit -> t
    let make ?(stream_id = {||}) () = (stream_id)
    let merge =
    let merge_stream_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "stream_id", "streamId"), string, ({||})) ) in
    fun (t1_stream_id) (t2_stream_id) -> merge_stream_id t1_stream_id t2_stream_id
    let spec () = Runtime'.Spec.( basic ((1, "stream_id", "streamId"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer (stream_id) -> serialize writer stream_id

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor stream_id = (stream_id) in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun (stream_id) -> serialize stream_id
    let from_json_exn =
      let constructor stream_id = (stream_id) in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and P_ResultInfo : sig
    type t = (string)
    val make: ?_tracelog_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?_tracelog_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = P_ResultInfo
    let name () = ".wandb_internal._ResultInfo"
    type t = (string)
    type make_t = ?_tracelog_id:string -> unit -> t
    let make ?(_tracelog_id = {||}) () = (_tracelog_id)
    let merge =
    let merge__tracelog_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((100, "_tracelog_id", "TracelogId"), string, ({||})) ) in
    fun (t1__tracelog_id) (t2__tracelog_id) -> merge__tracelog_id t1__tracelog_id t2__tracelog_id
    let spec () = Runtime'.Spec.( basic ((100, "_tracelog_id", "TracelogId"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer (_tracelog_id) -> serialize writer _tracelog_id

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor _tracelog_id = (_tracelog_id) in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun (_tracelog_id) -> serialize _tracelog_id
    let from_json_exn =
      let constructor _tracelog_id = (_tracelog_id) in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

end

