(********************************************************)
(*           AUTOGENERATED FILE - DO NOT EDIT!          *)
(********************************************************)
(* Generated by: ocaml-protoc-plugin                    *)
(* https://github.com/andersfugmann/ocaml-protoc-plugin *)
(********************************************************)
(*
  Source: wandb/proto/wandb_sync.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot=''
    opens=[]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
    prefix_output_with_package=false
*)
[@@@ocaml.alert "-protobuf"] (* Disable deprecation warnings for protobuf*)
(**/**)
module Runtime' = Ocaml_protoc_plugin [@@warning "-33"]
module Imported'modules = struct
  module Wandb_internal = Wandb_internal
  module Wandb_settings = Wandb_settings
end
(**/**)
module rec Wandb_internal : sig

  (**
{%html:
<p>Prepares a sync operation to replay one or more .wandb files.</p>
<p>The response is immediate and includes an ID to use in future requests.
A separate request starts the operation.</p>
%}
  *)
  module rec ServerInitSyncRequest : sig
    type t = {
      path:string list;
      (**
{%html:
<p>Paths to the .wandb files to upload.</p>
<p>Paths should either be absolute or relative to the cwd, and all paths
should refer to different files.</p>
%}
      *)

      settings:Imported'modules.Wandb_settings.Wandb_internal.Settings.t option;
      (**
{%html:
<p>Settings to use when syncing.</p>
%}
      *)

      new_entity:string;
      (**
{%html:
<p>An updated entity to use for all paths being synced.</p>
%}
      *)

      new_project:string;
      (**
{%html:
<p>An updated project to use for all paths being synced.</p>
%}
      *)

      new_run_id:string;
      (**
{%html:
<p>A new ID to use for all paths being synced.</p>
%}
      *)

      live:bool;
      (**
{%html:
<p>Whether to perform a live sync.</p>
%}
      *)

      cwd:string;
      (**
{%html:
<p>An absolute path to the user's current working directory.</p>
<p>Paths are displayed relative to this if the result is shorter.</p>
%}
      *)

      new_job_type:string;
      (**
{%html:
<p>A new job type to set for all runs being synced.</p>
%}
      *)

      tag_replacements:(string * string) list;
      (**
{%html:
<p>A map from old tag names to new ones.</p>
<p>Mapping a tag to an empty string deletes it.</p>
%}
      *)

    }
    val make: ?path:string list -> ?settings:Imported'modules.Wandb_settings.Wandb_internal.Settings.t -> ?new_entity:string -> ?new_project:string -> ?new_run_id:string -> ?live:bool -> ?cwd:string -> ?new_job_type:string -> ?tag_replacements:(string * string) list -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?path:string list -> ?settings:Imported'modules.Wandb_settings.Wandb_internal.Settings.t -> ?new_entity:string -> ?new_project:string -> ?new_run_id:string -> ?live:bool -> ?cwd:string -> ?new_job_type:string -> ?tag_replacements:(string * string) list -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end


  (**
{%html:
<p>Indicates a sync operation is ready.</p>
%}
  *)
  and ServerInitSyncResponse : sig
    type t = (string)
    (**
{%html:
<p>An ID to use to start and query the operation.</p>
%}
    *)

    val make: ?id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end


  (**
{%html:
<p>Begins a sync operation created by ServerInitSyncRequest.</p>
<p>The response is delivered once the operation completes.</p>
%}
  *)
  and ServerSyncRequest : sig
    type t = {
      id:string;
      (**
{%html:
<p>The operation's ID, as returned by ServerInitSyncResponse.</p>
%}
      *)

      parallelism:int;
      (**
{%html:
<p>How many runs to sync at once, if syncing multiple.</p>
<p>Syncing is generally IO bound, and the ideal parallelism depends
on factors like server performance and network speed.</p>
%}
      *)

    }
    val make: ?id:string -> ?parallelism:int -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?id:string -> ?parallelism:int -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end


  (**
{%html:
<p>Indicates a sync operation completed, either successfully or with errors.</p>
%}
  *)
  and ServerSyncResponse : sig
    type t = (ServerSyncMessage.t list)
    (**
{%html:
<p>Any messages that were not returned via a status response.</p>
%}
    *)

    val make: ?messages:ServerSyncMessage.t list -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?messages:ServerSyncMessage.t list -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end


  (**
{%html:
<p>Checks the status of an ongoing sync operation.</p>
%}
  *)
  and ServerSyncStatusRequest : sig
    type t = (string)
    (**
{%html:
<p>The operation's ID, as returned by ServerInitSyncResponse.</p>
%}
    *)

    val make: ?id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end


  (**
{%html:
<p>The status of a sync operation.</p>
%}
  *)
  and ServerSyncStatusResponse : sig
    type t = {
      stats:Imported'modules.Wandb_internal.Wandb_internal.OperationStats.t list;
      (**
{%html:
<p>The status of any ongoing work (such as network requests),
labeled by the run it's for.</p>
%}
      *)

      new_messages:ServerSyncMessage.t list;
      (**
{%html:
<p>New messages since the last status request.</p>
%}
      *)

    }
    val make: ?stats:Imported'modules.Wandb_internal.Wandb_internal.OperationStats.t list -> ?new_messages:ServerSyncMessage.t list -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?stats:Imported'modules.Wandb_internal.Wandb_internal.OperationStats.t list -> ?new_messages:ServerSyncMessage.t list -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end


  (**
{%html:
<p>ServerSyncMessage is a console message generated during a sync operation.</p>
%}
  *)
  and ServerSyncMessage : sig

    (**
{%html:
<p>Severity values match Python's logging module for convenience.</p>
%}
    *)
    module rec Severity : sig
      type t =
        | SEVERITY_NOTSET
        | SEVERITY_INFO
        | SEVERITY_WARNING
        | SEVERITY_ERROR

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    type t = {
      severity:Severity.t;
      content:string;
    }
    val make: ?severity:Severity.t -> ?content:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?severity:Severity.t -> ?content:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

end = struct
  module rec ServerInitSyncRequest : sig
    type t = {
      path:string list;
      (**
{%html:
<p>Paths to the .wandb files to upload.</p>
<p>Paths should either be absolute or relative to the cwd, and all paths
should refer to different files.</p>
%}
      *)

      settings:Imported'modules.Wandb_settings.Wandb_internal.Settings.t option;
      (**
{%html:
<p>Settings to use when syncing.</p>
%}
      *)

      new_entity:string;
      (**
{%html:
<p>An updated entity to use for all paths being synced.</p>
%}
      *)

      new_project:string;
      (**
{%html:
<p>An updated project to use for all paths being synced.</p>
%}
      *)

      new_run_id:string;
      (**
{%html:
<p>A new ID to use for all paths being synced.</p>
%}
      *)

      live:bool;
      (**
{%html:
<p>Whether to perform a live sync.</p>
%}
      *)

      cwd:string;
      (**
{%html:
<p>An absolute path to the user's current working directory.</p>
<p>Paths are displayed relative to this if the result is shorter.</p>
%}
      *)

      new_job_type:string;
      (**
{%html:
<p>A new job type to set for all runs being synced.</p>
%}
      *)

      tag_replacements:(string * string) list;
      (**
{%html:
<p>A map from old tag names to new ones.</p>
<p>Mapping a tag to an empty string deletes it.</p>
%}
      *)

    }
    val make: ?path:string list -> ?settings:Imported'modules.Wandb_settings.Wandb_internal.Settings.t -> ?new_entity:string -> ?new_project:string -> ?new_run_id:string -> ?live:bool -> ?cwd:string -> ?new_job_type:string -> ?tag_replacements:(string * string) list -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?path:string list -> ?settings:Imported'modules.Wandb_settings.Wandb_internal.Settings.t -> ?new_entity:string -> ?new_project:string -> ?new_run_id:string -> ?live:bool -> ?cwd:string -> ?new_job_type:string -> ?tag_replacements:(string * string) list -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = ServerInitSyncRequest
    let name () = ".wandb_internal.ServerInitSyncRequest"
    type t = {
      path:string list;
      settings:Imported'modules.Wandb_settings.Wandb_internal.Settings.t option;
      new_entity:string;
      new_project:string;
      new_run_id:string;
      live:bool;
      cwd:string;
      new_job_type:string;
      tag_replacements:(string * string) list;
    }
    type make_t = ?path:string list -> ?settings:Imported'modules.Wandb_settings.Wandb_internal.Settings.t -> ?new_entity:string -> ?new_project:string -> ?new_run_id:string -> ?live:bool -> ?cwd:string -> ?new_job_type:string -> ?tag_replacements:(string * string) list -> unit -> t
    let make ?(path = []) ?settings ?(new_entity = {||}) ?(new_project = {||}) ?(new_run_id = {||}) ?(live = false) ?(cwd = {||}) ?(new_job_type = {||}) ?(tag_replacements = []) () = { path; settings; new_entity; new_project; new_run_id; live; cwd; new_job_type; tag_replacements }
    let merge =
    let merge_path = Runtime'.Merge.merge Runtime'.Spec.( repeated ((1, "path", "path"), string, not_packed) ) in
    let merge_settings = Runtime'.Merge.merge Runtime'.Spec.( basic_opt ((2, "settings", "settings"), (message (module Imported'modules.Wandb_settings.Wandb_internal.Settings))) ) in
    let merge_new_entity = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "new_entity", "newEntity"), string, ({||})) ) in
    let merge_new_project = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "new_project", "newProject"), string, ({||})) ) in
    let merge_new_run_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((5, "new_run_id", "newRunId"), string, ({||})) ) in
    let merge_live = Runtime'.Merge.merge Runtime'.Spec.( basic ((6, "live", "live"), bool, (false)) ) in
    let merge_cwd = Runtime'.Merge.merge Runtime'.Spec.( basic ((7, "cwd", "cwd"), string, ({||})) ) in
    let merge_new_job_type = Runtime'.Merge.merge Runtime'.Spec.( basic ((8, "new_job_type", "newJobType"), string, ({||})) ) in
    let merge_tag_replacements = Runtime'.Merge.merge Runtime'.Spec.( map ((9, "tag_replacements", "tagReplacements"), (string, basic ((2, "value", "value"), string, ({||})))) ) in
    fun t1 t2 -> {
    	path = (merge_path t1.path t2.path);
    	settings = (merge_settings t1.settings t2.settings);
    	new_entity = (merge_new_entity t1.new_entity t2.new_entity);
    	new_project = (merge_new_project t1.new_project t2.new_project);
    	new_run_id = (merge_new_run_id t1.new_run_id t2.new_run_id);
    	live = (merge_live t1.live t2.live);
    	cwd = (merge_cwd t1.cwd t2.cwd);
    	new_job_type = (merge_new_job_type t1.new_job_type t2.new_job_type);
    	tag_replacements = (merge_tag_replacements t1.tag_replacements t2.tag_replacements);
     }
    let spec () = Runtime'.Spec.( repeated ((1, "path", "path"), string, not_packed) ^:: basic_opt ((2, "settings", "settings"), (message (module Imported'modules.Wandb_settings.Wandb_internal.Settings))) ^:: basic ((3, "new_entity", "newEntity"), string, ({||})) ^:: basic ((4, "new_project", "newProject"), string, ({||})) ^:: basic ((5, "new_run_id", "newRunId"), string, ({||})) ^:: basic ((6, "live", "live"), bool, (false)) ^:: basic ((7, "cwd", "cwd"), string, ({||})) ^:: basic ((8, "new_job_type", "newJobType"), string, ({||})) ^:: map ((9, "tag_replacements", "tagReplacements"), (string, basic ((2, "value", "value"), string, ({||})))) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { path; settings; new_entity; new_project; new_run_id; live; cwd; new_job_type; tag_replacements } -> serialize writer path settings new_entity new_project new_run_id live cwd new_job_type tag_replacements

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor path settings new_entity new_project new_run_id live cwd new_job_type tag_replacements = { path; settings; new_entity; new_project; new_run_id; live; cwd; new_job_type; tag_replacements } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { path; settings; new_entity; new_project; new_run_id; live; cwd; new_job_type; tag_replacements } -> serialize path settings new_entity new_project new_run_id live cwd new_job_type tag_replacements
    let from_json_exn =
      let constructor path settings new_entity new_project new_run_id live cwd new_job_type tag_replacements = { path; settings; new_entity; new_project; new_run_id; live; cwd; new_job_type; tag_replacements } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and ServerInitSyncResponse : sig
    type t = (string)
    (**
{%html:
<p>An ID to use to start and query the operation.</p>
%}
    *)

    val make: ?id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = ServerInitSyncResponse
    let name () = ".wandb_internal.ServerInitSyncResponse"
    type t = (string)
    type make_t = ?id:string -> unit -> t
    let make ?(id = {||}) () = (id)
    let merge =
    let merge_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "id", "id"), string, ({||})) ) in
    fun (t1_id) (t2_id) -> merge_id t1_id t2_id
    let spec () = Runtime'.Spec.( basic ((1, "id", "id"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer (id) -> serialize writer id

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor id = (id) in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun (id) -> serialize id
    let from_json_exn =
      let constructor id = (id) in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and ServerSyncRequest : sig
    type t = {
      id:string;
      (**
{%html:
<p>The operation's ID, as returned by ServerInitSyncResponse.</p>
%}
      *)

      parallelism:int;
      (**
{%html:
<p>How many runs to sync at once, if syncing multiple.</p>
<p>Syncing is generally IO bound, and the ideal parallelism depends
on factors like server performance and network speed.</p>
%}
      *)

    }
    val make: ?id:string -> ?parallelism:int -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?id:string -> ?parallelism:int -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = ServerSyncRequest
    let name () = ".wandb_internal.ServerSyncRequest"
    type t = {
      id:string;
      parallelism:int;
    }
    type make_t = ?id:string -> ?parallelism:int -> unit -> t
    let make ?(id = {||}) ?(parallelism = 0) () = { id; parallelism }
    let merge =
    let merge_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "id", "id"), string, ({||})) ) in
    let merge_parallelism = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "parallelism", "parallelism"), uint32_int, (0)) ) in
    fun t1 t2 -> {
    	id = (merge_id t1.id t2.id);
    	parallelism = (merge_parallelism t1.parallelism t2.parallelism);
     }
    let spec () = Runtime'.Spec.( basic ((1, "id", "id"), string, ({||})) ^:: basic ((2, "parallelism", "parallelism"), uint32_int, (0)) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { id; parallelism } -> serialize writer id parallelism

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor id parallelism = { id; parallelism } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { id; parallelism } -> serialize id parallelism
    let from_json_exn =
      let constructor id parallelism = { id; parallelism } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and ServerSyncResponse : sig
    type t = (ServerSyncMessage.t list)
    (**
{%html:
<p>Any messages that were not returned via a status response.</p>
%}
    *)

    val make: ?messages:ServerSyncMessage.t list -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?messages:ServerSyncMessage.t list -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = ServerSyncResponse
    let name () = ".wandb_internal.ServerSyncResponse"
    type t = (ServerSyncMessage.t list)
    type make_t = ?messages:ServerSyncMessage.t list -> unit -> t
    let make ?(messages = []) () = (messages)
    let merge =
    let merge_messages = Runtime'.Merge.merge Runtime'.Spec.( repeated ((1, "messages", "messages"), (message (module ServerSyncMessage)), not_packed) ) in
    fun (t1_messages) (t2_messages) -> merge_messages t1_messages t2_messages
    let spec () = Runtime'.Spec.( repeated ((1, "messages", "messages"), (message (module ServerSyncMessage)), not_packed) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer (messages) -> serialize writer messages

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor messages = (messages) in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun (messages) -> serialize messages
    let from_json_exn =
      let constructor messages = (messages) in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and ServerSyncStatusRequest : sig
    type t = (string)
    (**
{%html:
<p>The operation's ID, as returned by ServerInitSyncResponse.</p>
%}
    *)

    val make: ?id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = ServerSyncStatusRequest
    let name () = ".wandb_internal.ServerSyncStatusRequest"
    type t = (string)
    type make_t = ?id:string -> unit -> t
    let make ?(id = {||}) () = (id)
    let merge =
    let merge_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "id", "id"), string, ({||})) ) in
    fun (t1_id) (t2_id) -> merge_id t1_id t2_id
    let spec () = Runtime'.Spec.( basic ((1, "id", "id"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer (id) -> serialize writer id

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor id = (id) in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun (id) -> serialize id
    let from_json_exn =
      let constructor id = (id) in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and ServerSyncStatusResponse : sig
    type t = {
      stats:Imported'modules.Wandb_internal.Wandb_internal.OperationStats.t list;
      (**
{%html:
<p>The status of any ongoing work (such as network requests),
labeled by the run it's for.</p>
%}
      *)

      new_messages:ServerSyncMessage.t list;
      (**
{%html:
<p>New messages since the last status request.</p>
%}
      *)

    }
    val make: ?stats:Imported'modules.Wandb_internal.Wandb_internal.OperationStats.t list -> ?new_messages:ServerSyncMessage.t list -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?stats:Imported'modules.Wandb_internal.Wandb_internal.OperationStats.t list -> ?new_messages:ServerSyncMessage.t list -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = ServerSyncStatusResponse
    let name () = ".wandb_internal.ServerSyncStatusResponse"
    type t = {
      stats:Imported'modules.Wandb_internal.Wandb_internal.OperationStats.t list;
      new_messages:ServerSyncMessage.t list;
    }
    type make_t = ?stats:Imported'modules.Wandb_internal.Wandb_internal.OperationStats.t list -> ?new_messages:ServerSyncMessage.t list -> unit -> t
    let make ?(stats = []) ?(new_messages = []) () = { stats; new_messages }
    let merge =
    let merge_stats = Runtime'.Merge.merge Runtime'.Spec.( repeated ((1, "stats", "stats"), (message (module Imported'modules.Wandb_internal.Wandb_internal.OperationStats)), not_packed) ) in
    let merge_new_messages = Runtime'.Merge.merge Runtime'.Spec.( repeated ((2, "new_messages", "newMessages"), (message (module ServerSyncMessage)), not_packed) ) in
    fun t1 t2 -> {
    	stats = (merge_stats t1.stats t2.stats);
    	new_messages = (merge_new_messages t1.new_messages t2.new_messages);
     }
    let spec () = Runtime'.Spec.( repeated ((1, "stats", "stats"), (message (module Imported'modules.Wandb_internal.Wandb_internal.OperationStats)), not_packed) ^:: repeated ((2, "new_messages", "newMessages"), (message (module ServerSyncMessage)), not_packed) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { stats; new_messages } -> serialize writer stats new_messages

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor stats new_messages = { stats; new_messages } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { stats; new_messages } -> serialize stats new_messages
    let from_json_exn =
      let constructor stats new_messages = { stats; new_messages } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and ServerSyncMessage : sig

    (**
{%html:
<p>Severity values match Python's logging module for convenience.</p>
%}
    *)
    module rec Severity : sig
      type t =
        | SEVERITY_NOTSET
        | SEVERITY_INFO
        | SEVERITY_WARNING
        | SEVERITY_ERROR

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    type t = {
      severity:Severity.t;
      content:string;
    }
    val make: ?severity:Severity.t -> ?content:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?severity:Severity.t -> ?content:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = ServerSyncMessage
    module rec Severity : sig
      type t =
        | SEVERITY_NOTSET
        | SEVERITY_INFO
        | SEVERITY_WARNING
        | SEVERITY_ERROR

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end = struct
      module This'_ = Severity
      type t =
        | SEVERITY_NOTSET
        | SEVERITY_INFO
        | SEVERITY_WARNING
        | SEVERITY_ERROR

      let name () = ".wandb_internal.ServerSyncMessage.Severity"
      let to_int = function
        | SEVERITY_NOTSET -> 0
        | SEVERITY_INFO -> 20
        | SEVERITY_WARNING -> 30
        | SEVERITY_ERROR -> 40
      let from_int_exn = function
        | 0 -> SEVERITY_NOTSET
        | 20 -> SEVERITY_INFO
        | 30 -> SEVERITY_WARNING
        | 40 -> SEVERITY_ERROR
        | n -> Runtime'.Result.raise (`Unknown_enum_value n)
      let from_int e = Runtime'.Result.catch (fun () -> from_int_exn e)
      let to_string = function
        | SEVERITY_NOTSET -> "SEVERITY_NOTSET"
        | SEVERITY_INFO -> "SEVERITY_INFO"
        | SEVERITY_WARNING -> "SEVERITY_WARNING"
        | SEVERITY_ERROR -> "SEVERITY_ERROR"
      let from_string_exn = function
        | "SEVERITY_NOTSET" -> SEVERITY_NOTSET
        | "SEVERITY_INFO" -> SEVERITY_INFO
        | "SEVERITY_WARNING" -> SEVERITY_WARNING
        | "SEVERITY_ERROR" -> SEVERITY_ERROR
        | s -> Runtime'.Result.raise (`Unknown_enum_name s)

    end

    let name () = ".wandb_internal.ServerSyncMessage"
    type t = {
      severity:Severity.t;
      content:string;
    }
    type make_t = ?severity:Severity.t -> ?content:string -> unit -> t
    let make ?(severity = Severity.from_int_exn 0) ?(content = {||}) () = { severity; content }
    let merge =
    let merge_severity = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "severity", "severity"), (enum (module Severity)), (Severity.from_int_exn 0)) ) in
    let merge_content = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "content", "content"), string, ({||})) ) in
    fun t1 t2 -> {
    	severity = (merge_severity t1.severity t2.severity);
    	content = (merge_content t1.content t2.content);
     }
    let spec () = Runtime'.Spec.( basic ((1, "severity", "severity"), (enum (module Severity)), (Severity.from_int_exn 0)) ^:: basic ((2, "content", "content"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { severity; content } -> serialize writer severity content

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor severity content = { severity; content } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { severity; content } -> serialize severity content
    let from_json_exn =
      let constructor severity content = { severity; content } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

end

